// Errors
export const GET_ERRORS = "GET_ERRROS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
// Users
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
// Organization
export const ORGANIZATION_LOADING = "ORGANIZATION_LOADING";
export const GET_ORGANIZATIONS = "GET_ORGANIZATIONS";
export const GET_ORGANIZATION = "GET_ORGANIZATION";
export const ADD_ORGANIZATION = "ADD_ORGANIZATION";
export const UPDATE_ORGANIZATION = "UPDATE_ORGANIZATION";
export const DELETE_ORGANIZATION = "DELETE_ORGANIZATION";
