// Errors
export const GET_ERRORS = "GET_ERRROS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
// Users
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const COUNT_RECORD = "COUNT_RECORD";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
// Organization
export const ORGANIZATION_LOADING = "ORGANIZATION_LOADING";
export const GET_ORGANIZATIONS = "GET_ORGANIZATIONS";
export const GET_ORGANIZATION = "GET_ORGANIZATION";
export const UPDATE_ORGANIZATION = "UPDATE_ORGANIZATION";
export const DELETE_ORGANIZATION = "DELETE_ORGANIZATION";
// Lead
export const LEAD_LOADING = "LEAD_LOADING";
export const GET_LEADS = "GET_LEADS";
export const GET_LEAD = "GET_LEAD";
export const UPDATE_LEAD = "UPDATE_LEAD";
export const DELETE_LEAD = "DELETE_LEAD";
// Contact
export const CONTACT_LOADING = "CONTACT_LOADING";
export const GET_CONTACTS = "GET_CONTACTS";
export const GET_CONTACT = "GET_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
// Opportunity
export const OPPORTUNITY_LOADING = "OPPORTUNITY_LOADING";
export const GET_OPPORTUNITIES = "GET_OPPORTUNITIES";
export const GET_OPPORTUNITY = "GET_OPPORTUNITY";
export const UPDATE_OPPORTUNITY = "UPDATE_OPPORTUNITY";
export const DELETE_OPPORTUNITY = "DELETE_OPPORTUNITY";
export const GET_CONTACT_OPPORTUNITIES = "GET_CONTACT_OPPORTUNIIES";
